Repository IATI/IATI-Extra-Documentation, pull requests merged in 2018-03, with the labels that each got.

#438 Fix some build warnings (v2.03)
  en/activity-standard/iati-activities/iati-activity/result/indicator/baseline/dimension.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/baseline/location.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/target/location.rst
  en/activity-standard/iati-activities/iati-activity/sector.rst
  en/activity-standard/iati-activities/iati-activity/tag.rst
Labels: 2.03, code examples, complete, requires replication to version branches

#449 Fix some build warnings (v2.02)
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/actual/dimension.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/actual/location.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/target/dimension.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/target/location.rst
  en/activity-standard/iati-activities/iati-activity/sector.rst
  en/activity-standard/iati-activities/iati-activity/transaction/sector.rst
Labels: 2.02

#450 Fix some build warnings (v1.05)
  en/activity-standard/iati-activities/iati-activity/planned-disbursement/period-start.rst
  en/organisation-standard/iati-organisations/iati-organisation/recipient-country-budget.rst
Labels: 1.05

#451 Fix some build warnings (v1.04)
  en/activity-standard/iati-activities/iati-activity/planned-disbursement/period-start.rst
  en/organisation-standard/iati-organisations/iati-organisation/recipient-country-budget.rst
Labels: 1.04

#436 Fix typo in changelog; fix link in changelog (v2.03)
  en/activity-standard/iati-activities/iati-activity/document-link/document-date.rst
Labels: 2.03

#454 Fix typo in changelog; fix link in changelog (v2.02)
  en/activity-standard/iati-activities/iati-activity/document-link/document-date.rst
Labels: 2.02

#434 Remove ref to multi example (v2.03)
  en/activity-standard/example-xml.rst
Labels: 2.03, requires replication to version branches

#447 Remove ref to multi example (v2.02)
  en/activity-standard/example-xml.rst
Labels: 2.02

#448 Remove ref to multi example (v2.01)
  en/activity-standard/example-xml.rst
Labels: 2.01

#442 Fix example usage (v2.03)
  en/organisation-standard/iati-organisations/iati-organisation/document-link/description/narrative.rst
Labels: 2.03

#422 Use valid sector codes in examples (v1.05)
  en/activity-standard/activity-standard-example-annotated-multi.xml
  en/activity-standard/activity-standard-example-annotated.xml
Labels: 1.05

#444 remove 2.01 notice (2.01)
  en/activity-standard/overview/contact-info.rst
Labels: 2.01

#443 remove 2.01 notice (2.02)
  en/activity-standard/overview/contact-info.rst
Labels: 2.02

#432 Create all-elements-in-IATI.rst
  en/activity-standard/overview/all-elements-in-IATI.rst
Labels: 2.03, bug, complete

#431 Adding in two missing page links
  en/activity-standard/overview.rst
Labels: 2.03, bug, complete

#430 Create what-to-publish.rst
  en/activity-standard/overview/what-to-publish.rst
Labels: 2.03, bug, complete

#440 Remove v2.01 release notice (v2.03)
  en/activity-standard/overview/contact-info.rst
Labels: 2.03

#424 Update budget definition
  en/activity-standard/overview/budgets.rst
Labels: bug, complete

#426 update budget guidance
  en/activity-standard/overview/transactions.rst
Labels: bug, complete

#423 Update budget guidance
  en/activity-standard/overview/budgets.rst
Labels: bug, complete

#425 update budget guidance
  en/activity-standard/overview/transactions.rst
Labels: bug, complete

#427 Add budget def change to changelog
  en/activity-standard/iati-activities/iati-activity/budget.rst
Labels: bug, complete

#472 Change heading style
  en/codelists/PolicySignificance.rst
Labels: 2.02
