Repository IATI/IATI-Extra-Documentation, pull requests merged in 2018-02, with the labels that each got.

#396 2.03 occurrence aid type 351
  en/activity-standard/iati-activities/iati-activity/transaction/aid-type.rst
Labels: 2.03, complete

#397 2.03 occurrence default aid type 350
  en/activity-standard/iati-activities/iati-activity/default-aid-type.rst
Labels: 2.03, complete

#398 2.03 definition capital spend percentage
  en/activity-standard/iati-activities/iati-activity/capital-spend.rst
Labels: 2.03, complete

#399 2.03 definition related activity 349
  en/activity-standard/iati-activities/iati-activity/related-activity.rst
Labels: 2.03, complete

#400 2.03 def indicator uri 347
  en/activity-standard/iati-activities/iati-activity/result/indicator/reference.rst
Labels: 2.03, complete

#401 2.03 add vocab attribute for aid type 346
  en/activity-standard/activity-standard-example-annotated.xml
  en/activity-standard/iati-activities/iati-activity/default-aid-type.rst
  en/activity-standard/iati-activities/iati-activity/transaction/aid-type.rst
Labels: 2.03, complete

#402 2.03 def aid type code 345
  en/activity-standard/activity-standard-example-annotated.xml
  en/activity-standard/iati-activities/iati-activity/default-aid-type.rst
  en/activity-standard/iati-activities/iati-activity/document-link.rst
  en/activity-standard/iati-activities/iati-activity/transaction/aid-type.rst
Labels: 2.03, complete

#403 2.03 defin sector vocab attribute 344
  en/activity-standard/iati-activities/iati-activity/sector.rst
Labels: 2.03, complete

#405 2.03 defin recipient region vocab uri 341
  en/activity-standard/iati-activities/iati-activity/recipient-region.rst
  en/activity-standard/iati-activities/iati-activity/transaction/recipient-region.rst
  en/organisation-standard/iati-organisations/iati-organisation/recipient-region-budget/recipient-region.rst
Labels: 2.03, complete

#406 2.03 new tag element 342 plus document-link/description
  en/activity-standard/activity-standard-example-annotated.xml
  en/activity-standard/iati-activities/iati-activity/document-link/description.rst
  en/activity-standard/iati-activities/iati-activity/tag.rst
  en/activity-standard/iati-activities/iati-activity/tag/narrative.rst
Labels: 2.03, complete

#407 2.03 update defin 2ndry reporter 340
  en/activity-standard/iati-activities/iati-activity/reporting-org.rst
Labels: 2.03, complete

#408 2.03 update 2ndry reporter org file 340
  en/organisation-standard/iati-organisations/iati-organisation/reporting-org.rst
Labels: 2.03, complete

#409 2.03 update def of @ref attribute 339
  en/activity-standard/iati-activities/iati-activity/participating-org.rst
  en/activity-standard/iati-activities/iati-activity/planned-disbursement/provider-org.rst
  en/activity-standard/iati-activities/iati-activity/planned-disbursement/receiver-org.rst
  en/activity-standard/iati-activities/iati-activity/transaction/provider-org.rst
  en/activity-standard/iati-activities/iati-activity/transaction/receiver-org.rst
  en/organisation-standard/iati-organisations/iati-organisation/organisation-identifier.rst
  en/organisation-standard/iati-organisations/iati-organisation/recipient-org-budget/recipient-org.rst
Labels: 2.03, complete

#410 2.03 add attr crs channel code 338
  en/activity-standard/activity-standard-example-annotated.xml
  en/activity-standard/iati-activities/iati-activity/participating-org.rst
Labels: 2.03, complete

#411 2.03 add budget not provided attribute 337
  en/activity-standard/activity-standard-example-annotated.xml
  en/activity-standard/iati-activities/iati-activity.rst
Labels: 2.03, complete

#412 2.03 amy checks and additions
  en/activity-standard/iati-activities/iati-activity/humanitarian-scope.rst
  en/activity-standard/iati-activities/iati-activity/policy-marker.rst
  en/activity-standard/iati-activities/iati-activity/reporting-org.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/reference.rst
  en/activity-standard/iati-activities/iati-activity/sector.rst
  en/activity-standard/iati-activities/iati-activity/tag/narrative.rst
  en/activity-standard/iati-activities/iati-activity/transaction/sector.rst
  en/organisation-standard/iati-organisations/iati-organisation/reporting-org.rst
Labels: 2.03, complete

#415 Remove emphasize-lines
  en/activity-standard/iati-activities/iati-activity/document-link/description.rst
  en/activity-standard/iati-activities/iati-activity/document-link/description/narrative.rst
  en/activity-standard/iati-activities/iati-activity/result/document-link.rst
  en/activity-standard/iati-activities/iati-activity/result/document-link/category.rst
  en/activity-standard/iati-activities/iati-activity/result/document-link/description.rst
  en/activity-standard/iati-activities/iati-activity/result/document-link/description/narrative.rst
  en/activity-standard/iati-activities/iati-activity/result/document-link/document-date.rst
  en/activity-standard/iati-activities/iati-activity/result/document-link/language.rst
  en/activity-standard/iati-activities/iati-activity/result/document-link/title.rst
  en/activity-standard/iati-activities/iati-activity/result/document-link/title/narrative.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/baseline/dimension.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/baseline/document-link.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/baseline/document-link/category.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/baseline/document-link/description.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/baseline/document-link/description/narrative.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/baseline/document-link/document-date.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/baseline/document-link/language.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/baseline/document-link/title.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/baseline/document-link/title/narrative.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/baseline/location.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/document-link.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/document-link/category.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/document-link/description.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/document-link/description/narrative.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/document-link/document-date.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/document-link/language.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/document-link/title.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/document-link/title/narrative.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/actual/document-link.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/actual/document-link/category.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/actual/document-link/description.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/actual/document-link/description/narrative.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/actual/document-link/document-date.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/actual/document-link/language.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/actual/document-link/title.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/actual/document-link/title/narrative.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/target/document-link.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/target/document-link/category.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/target/document-link/description.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/target/document-link/description/narrative.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/target/document-link/document-date.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/target/document-link/language.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/target/document-link/title.rst
  en/activity-standard/iati-activities/iati-activity/result/indicator/period/target/document-link/title/narrative.rst
  en/activity-standard/iati-activities/iati-activity/result/reference.rst
  en/organisation-standard/iati-organisations/iati-organisation/document-link/description/narrative.rst
Labels: 2.03, code examples, complete

#416 Change version number in 2.03 example XML
  en/activity-standard/activity-standard-example-annotated.xml
Labels: 2.03, bug, complete

#419 Change references to 2.02 to 2.03
  en/activity-standard/activity-standard-example-annotated.xml
  en/organisation-standard/example-xml.rst
  en/organisation-standard/organisation-standard-example-annotated.xml
Labels: 2.03, Documentation, complete
